# Generated by Django 2.1.2 on 2018-11-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_num',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
