# Generated by Django 2.1.2 on 2018-11-13 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0003_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='men.Order'),
        ),
        migrations.AlterField(
            model_name='get',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='men.Product'),
        ),
    ]
