# Generated by Django 2.1.2 on 2018-11-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0004_auto_20181114_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='get',
            name='value',
        ),
    ]
