# Generated by Django 2.1.2 on 2018-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0005_remove_get_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='get',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
