# Generated by Django 2.1.2 on 2018-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0009_auto_20181120_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
