# Generated by Django 2.1.2 on 2018-11-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0010_auto_20181121_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
