# Generated by Django 2.1.2 on 2018-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0012_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
