# Generated by Django 2.1.2 on 2018-11-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0013_auto_20181124_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='address',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='rest',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rest',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
