# Generated by Django 2.1.2 on 2018-11-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0014_auto_20181124_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='logo',
            field=models.ImageField(blank=True, upload_to=' Profile_image'),
        ),
    ]
