# Generated by Django 2.1.2 on 2018-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0019_auto_20181205_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lan',
            field=models.IntegerField(default=0),
        ),
    ]
