# Generated by Django 2.1.2 on 2018-12-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0021_langen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arname', models.CharField(max_length=15)),
                ('ardescription', models.TextField(max_length=60)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='men.Product')),
            ],
        ),
    ]
