# Generated by Django 2.1.2 on 2018-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0023_auto_20181206_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' Profile_image'),
        ),
    ]
