# Generated by Django 2.1.2 on 2018-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0024_auto_20181207_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rest',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=' Profile_image'),
        ),
    ]
