# Generated by Django 2.1.2 on 2018-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0025_auto_20181207_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=' Profile_image'),
        ),
    ]
