# Generated by Django 2.1.2 on 2018-12-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0026_auto_20181207_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='Language',
            field=models.IntegerField(default=1),
        ),
    ]
