# Generated by Django 2.1.2 on 2018-12-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0027_rest_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='men.Order'),
        ),
        migrations.AlterField(
            model_name='get',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='men.Product'),
        ),
    ]
