# Generated by Django 2.1.2 on 2018-12-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0028_auto_20181208_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_num',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
