# Generated by Django 2.1.2 on 2018-12-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0032_auto_20181209_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
