# Generated by Django 2.1.2 on 2019-01-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0035_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
